export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILURE = "FETCH_TEAMS_FAILURE";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";
export const EDIT_TEAM_SUCCESS = "EDIT_TEAM_SUCCESS";
export const EDIT_TEAM_FAILURE = "EDIT_TEAM_FAILURE";

export const FETCH_REFEREE_REQUEST = "FETCH_REFEREE_REQUEST";
export const FETCH_REFEREE_SUCCESS = "FETCH_REFEREE_SUCCESS";
export const FETCH_REFEREE_FAILURE = "FETCH_REFEREE_FAILURE";
export const ADD_REFEREE_SUCCESS = "ADD_REFEREE_SUCCESS";
export const ADD_REFEREE_FAILURE = "ADD_REFEREE_FAILURE";
export const EDIT_REFEREE_SUCCESS = "EDIT_REFEREE_SUCCESS";
export const EDIT_REFEREE_FAILURE = "EDIT_REFEREE_FAILURE";

export const PLAY_MUSIC = "PLAY_MUSIC";
export const PAUSE_MUSIC = "PAUSE_MUSIC"