// TEAM

export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILURE = "FETCH_TEAMS_FAILURE";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";
export const EDIT_TEAM_SUCCESS = "EDIT_TEAM_SUCCESS";
export const EDIT_TEAM_FAILURE = "EDIT_TEAM_FAILURE";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";

export const FETCH_TEAM_DETAILS_REQUEST = "FETCH_TEAM_DETAILS_REQUEST";
export const FETCH_TEAM_DETAILS_SUCCESS = "FETCH_TEAM_DETAILS_SUCCESS";
export const FETCH_TEAM_DETAILS_FAILURE = "FETCH_TEAM_DETAILS_FAILURE";

export const FETCH_TEAM_COACH_REQUEST = "FETCH_TEAM_COACH_REQUEST";
export const FETCH_TEAM_COACH_SUCCESS = "FETCH_TEAM_COACH_SUCCESS";
export const FETCH_TEAM_COACH_FAILURE = "FETCH_TEAM_COACH_FAILURE";

// REFEREE

export const FETCH_REFEREE_REQUEST = "FETCH_REFEREE_REQUEST";
export const FETCH_REFEREE_SUCCESS = "FETCH_REFEREE_SUCCESS";
export const FETCH_REFEREE_FAILURE = "FETCH_REFEREE_FAILURE";
export const ADD_REFEREE_SUCCESS = "ADD_REFEREE_SUCCESS";
export const ADD_REFEREE_FAILURE = "ADD_REFEREE_FAILURE";
export const EDIT_REFEREE_SUCCESS = "EDIT_REFEREE_SUCCESS";
export const EDIT_REFEREE_FAILURE = "EDIT_REFEREE_FAILURE";
export const DELETE_REFEREE_SUCCESS = 'DELETE_REFEREE_SUCCESS';
export const DELETE_REFEREE_FAILURE = 'DELETE_REFEREE_FAILURE';

// MAIN MUSIC

export const PLAY_MUSIC = "PLAY_MUSIC";
export const PAUSE_MUSIC = "PAUSE_MUSIC"

// PLAYER

export const FETCH_PLAYERS_REQUEST = "FETCH_PLAYERS_REQUEST";
export const FETCH_PLAYERS_SUCCESS = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_FAILURE = "FETCH_PLAYERS_FAILURE";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAILURE = "ADD_PLAYER_FAILURE";
export const EDIT_PLAYER_SUCCESS = "EDIT_PLAYER_SUCCESS";
export const EDIT_PLAYER_FAILURE = "EDIT_PLAYER_FAILURE";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_FAILURE = "DELETE_PLAYER_FAILURE";

export const FETCH_PLAYER_POSITIONS_SUCCESS = 'FETCH_PLAYER_POSITIONS_SUCCESS';

export const SEARCH_PLAYERS_REQUEST = 'SEARCH_PLAYERS_REQUEST';
export const SEARCH_PLAYERS_SUCCESS = 'SEARCH_PLAYERS_SUCCESS';
export const SEARCH_PLAYERS_FAILURE = 'SEARCH_PLAYERS_FAILURE';

// COACH

export const FETCH_COACHES_REQUEST = "FETCH_COACHES_REQUEST";
export const FETCH_COACHES_SUCCESS = "FETCH_COACHES_SUCCESS";
export const FETCH_COACHES_FAILURE = "FETCH_COACHES_FAILURE";
export const ADD_COACH_SUCCESS = "ADD_COACH_SUCCESS";
export const ADD_COACH_FAILURE = "ADD_COACH_FAILURE";
export const EDIT_COACH_SUCCESS = "EDIT_COACH_SUCCESS";
export const EDIT_COACH_FAILURE = "EDIT_COACH_FAILURE";
export const DELETE_COACH_SUCCESS = "DELETE_COACH_SUCCESS";
export const DELETE_COACH_FAILURE = "DELETE_COACH_FAILURE";

// SIDEBAR

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// ENTITY

export const DELETE_ENTITY_SUCCESS = "DELETE_ENTITY_SUCCESS";
export const DELETE_ENTITY_FAILURE = "DELETE_ENTITY_FAILURE";